### ISSUE TITLE
Naming chunks, suppressing msColl output

### ISSUE THREAD

**Issue by raffazizzi** [FrankensteinVariorum/fv-postCollation#10]
I'll be replacing fMS chunks with files that include specific S-GA files. To do this properly I think we should:

1. adjust naming to remove P5 (e.g. from `P5-f1818_C01.xml` to  `f1818_C01.xml`)
2. do **not** generate fMS files so that a possible re-run wouldn't overwrite the chunk files that I'll be adding

**Comment by ebeshero** [comment]
@raffazizzi I'm increasingly reluctant to suppress msColl output files for a couple of reasons: 
1) long-range: They represent semantic resequencing of S-GA, and might be valuable for querying. We may want to consult them internally in the project team, much like we need to consult the P1 files.
2) short-range: The processes generating the output editions, in the last stages, run in the shell so I'm not defining collection variables to run these, just running over a directory.

I think the easier course here might just be to *move* these files to an alternative directory, not being used in the Variorum interface. That's the action I'm taking now, and I'll add it as a stage in my instructions on the pipeline process for fv-postCollation.

**Comment by ebeshero** [comment]
@raffazizzi Success! With [this commit](https://github.com/PghFrankenstein/fv-postCollation/commit/ece946427d25a33ec7401b9239d8af6389904989), I've set up [a script](https://github.com/PghFrankenstein/fv-postCollation/blob/master/postColl-workspace/migrateP5msColl.sh) that: 
1) separates my pipeline-processed MS edition files into their own distinct directory: [P5-MS](https://github.com/PghFrankenstein/fv-postCollation/tree/master/postColl-workspace/P5-MS)
2) prepares a directory with only the print edition files: [P5-print](https://github.com/PghFrankenstein/fv-postCollation/tree/master/postColl-workspace/P5-print) 
3) removes the `P5-` prefix from all file names in both new directories
4) copies the new directories over to the  `fv-data` repo as:
  * [fv-data/variorum-chunks](https://github.com/PghFrankenstein/fv-data/tree/master/variorum-chunks)  (for files prepped for the Variorum interface, at this point containing only print edition files)
  * [fv-data/reseqMS-chunks](https://github.com/PghFrankenstein/fv-data/tree/master/reseqMS-chunks) (for MS output files, resequenced/altered from their original S-GA form during the collation process--not to be used in the Variorum interface, but potentially helpful for reference and research.)

Finally, with [this commit](https://github.com/PghFrankenstein/fv-postCollation/commit/3680957c7d94da4a18f58346b2bcb1669529b080), I've updated the README outlining our postCollation pipeline. Hope this works--I'm leaving this open until you review it.

**Comment by ebeshero** [comment]
Updated to add links to script and new directories in case we want to change directory names, etc.

**Comment by raffazizzi** [comment]
@ebeshero my suggestion was to keep all of the intermediate files, but to still have one place (I'd say one repository) that only contains the final shape of the data, ie the data that the interface will use and that will represent the completed variorum edition.

**Comment by ebeshero** [comment]
@raffazizzi That makes sense, yes. I think we should treat this fv-postCollation repo as containing the intermediate stage files, and fv-data will then not contain the MS collated files.
