### ISSUE TITLE
TEI spines have old URLs to novel files

### ISSUE THREAD

**Issue by raffazizzi** [FrankensteinVariorum/fv-postCollation#11]
E.g. 
`<ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/edition-chunks/P5-f1818_C10.xml#C10_app9-f1818"/>`

should be

`<ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1818_C10.xml#C10_app9-f1818"/>`

**Comment by ebeshero** [comment]
Transferred to the postCollation repo where I need to change the P5_SpineGenerator.xsl to repair the links.

**Comment by ebeshero** [comment]
Re-run full pipeline with correct output, with https://github.com/PghFrankenstein/fv-postCollation/commit/1db6ac8f9bf02c8a4004747570c2ec42dc15a7d7  
Links are repaired!
