### ISSUE TITLE
Fix output of Chapter Headings to prevent duplicate seg ids

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#26]
Chapter heading `<seg>` markers are coming out with the same id as the very first content `<seg>`. Debug this in the XSLT

**Comment by ebeshero** [comment]
@Yuying-Jin Is this the same problem that we looked at today in https://github.com/FrankensteinVariorum/fv-web2023/issues/4 ?

Perhaps it is only a problem for chapters coming from the old Collation units C01 to C10.

**Comment by Yuying-Jin** [comment]
> @Yuying-Jin Is this the same problem that we looked at today in [FrankensteinVariorum/fv-web2023#4](https://github.com/FrankensteinVariorum/fv-web2023/issues/4) ?
> 
> Perhaps it is only a problem for chapters coming from the old Collation units C01 to C10.

@ebeshero No, they are different. To solve the problems about the same seg ids, I need to restore `I`, `M`, and `F`, which I removed before, in the seg id.
