### ISSUE TITLE
Lev values too high? 

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#28]
@Yuying-Jin and I discover that current outputs of Levenshtein distances look to be based on raw string counts instead of literal edit distances. The outputs from ~2020 look reasonable, though. We should investigate whether our Python weighted-Levenshtein library is missing something or out of date.

**Comment by Yuying-Jin** [comment]
install the lastest version with `pip install weighted-levenshtein`

**Comment by ebeshero** [comment]
Resolved with https://github.com/FrankensteinVariorum/fv-postCollation/pull/29 

Our Levenshtein calculations were correct, but we needed to get rid or the NoRdg placeholders which unduly exaggerated the values. This involved restoring a step we had recently left out of our postCollation pipeline.
