### ISSUE TITLE
MS chapter files to rename in pipeline

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#36]
We discover that there is no "magic bullet" XSLT to correctly capture all the chapter file names from the MS. But there are only three files (so far) whose names are a little too short using our mostly-good XPath. We need to rename the following fMS chapter output files.

The files are:
* fMS_box_c56_chapter :: C08
* fMS_box_c57_vol_ii:: C17
* fMS_box_c57_chap.xml:: C25

- [x]  Investigate what the name should be by inspecting the file
- [x]  Then correct its filename as a stage in the postCollation pipeline.

**Comment by Yuying-Jin** [comment]
fMS chapter files are fixed so far:
fMS_box_c56_chapter.xml --> fMS_box_c56_chapter_3.xml
fMS_box_c57_vol_ii.xml --> fMS_box_c57_vol_ii_chap_i.xml
fMS_box_c57_chap.xml --> fMS_box_c57_chap_2.xml

**Comment by ebeshero** [comment]
@Yuying-Jin should the filename use a Roman numeral for the chapter number to be consistent with the other chapter files?

**Comment by ebeshero** [comment]
This may now be resolved with this commit: https://github.com/FrankensteinVariorum/fv-postCollation/commit/604b5493cfc9e46ce5b8b671a6e7a7e41ff896b9 
Here we have added a step in the postCollation Pipeline to output the links to these three filenames properly.

**Comment by ebeshero** [comment]
Actually repaired now with this commit: https://github.com/FrankensteinVariorum/fv-postCollation/commit/f5ba83863703f89a2832e7eb65c538590fc515d2
