### ISSUE TITLE
Adding URLs for Morgan Thomas facsimile pages 

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#39]
- [x]  Write an XSLT that generates a simple standoff file from the P6-P2 Thomas XML file to:

     * store a list of the special Thomas `<note>` elements with `@ana='start'`. 
     * Also output their location info by finding one of these XPaths:
          * If a descendant of `<p>`: `//note[@ana='start']/ancestor::p/@xml:id`
          * If not a descendant of `<p>`: `//note[@ana='start'][not(ancestor::p)]/preceding::*[not(name(.) = 'seg')][1]/@xml:id`

- [ ] (After our re-launch) We should contact the Huntington to let them know we're linking to their pages (to encourage them to keep their site live and link to us

**Comment by ebeshero** [comment]
To make the information better searchable, add these things to the XSLT:

- [ ] Nearest preceding volume
- [ ] Nearest preceding chapter heading 
- [x] nearest preceding `<pb/>` (page-beginning) number value.

**Comment by ebeshero** [comment]
@Yuying-Jin has an idea to make this go faster with a package for typescript and looking just for the nearest preceding page number, then finding the link on the Thumbnails page:
https://www.themorgan.org/collection/frankenstein/thumbs

**Comment by ebeshero** [comment]
Puppeteer (which @Yuying-Jin  found): https://pptr.dev/

**Comment by Yuying-Jin** [comment]
See [pull request](https://github.com/FrankensteinVariorum/fv-postCollation/pull/41)

**Comment by ebeshero** [comment]
I'm closing this because the work of linking to the Morgan library pages is complete. I'll open a new ticket about contacting the Morgan, with other formal launch-release tasks.
