### ISSUE TITLE
Inconsistent Namespace in XSLT Files

### ISSUE THREAD

**Issue by Yuying-Jin** [FrankensteinVariorum/fv-postCollation#40]
@ebeshero The XSLT files exhibit inconsistency in their namespaces. The XSLT files are suffering from an issue where some namespaces are being added as attributes to elements in output files. For instance, some elements are appearing with additional namespace attributes like:
```xml
<lb xmlns:mith="http://mith.umd.edu/sc/ns1#"
    xmlns:pitt="https://github.com/ebeshero/Pittsburgh_Frankenstein"
    xmlns:th="http://www.blackmesatech.com/2017/nss/trojan-horse"
    n="c56-0011__main__1"/>
```

**Comment by ebeshero** [comment]
I believe we have now resolved these issues in the pipeline with our work in August.
