### ISSUE TITLE
normalizing the double underscores in filename

### ISSUE THREAD

**Issue by Yuying-Jin** [FrankensteinVariorum/fv-postCollation#42]
During the website building process, the generator normalized the double underscores in chapter filenames, converting them to single underscores. This caused a problem where certain chapter pages cannot be found because the original filenames contained double underscores.

For example, the original filename `box_c56_ch_v__113` was normalized to `box_c56_ch_v_113`, which might cause a mismatch when trying to access the corresponding chapter page.

To resolve this issue, we need to normalize the double underscores in the chapter filenames in post-collation. By doing so, the chapter pages will be correctly linked and accessible on the website.

**Comment by ebeshero** [comment]
Completed.
