### ISSUE TITLE
multiply-defined ID

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/fv-postCollation#5]
In `P1-output/P1_C06h.xml`, `xml:id` `C06h_app1_rg1` is defined twice

**Comment by ebeshero** [comment]
@mdlincoln Yes--thank you! I opened an issue on this in an earlier-stage repo because it's something I need to correct there first--but make sure the results get moved here. https://github.com/PghFrankenstein/Pittsburgh_Frankenstein/issues/65

**Comment by ebeshero** [comment]
Repaired in earlier stages: This multiply-defined ID was the result of a nested `<rdgGrp>` from editing the collation output. I've corrected and fended off future errors like this by adding a Schematron rule to flag nested rdgGrp elements. (These need to all be at the same level.)
