### ISSUE TITLE
processing delSpan elements

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#51]
We are running into problems with outputting passages marked by `<delSpan spanTo="somewhere">......</delSpan anchor="#somewhere">`. (This is our FV adjustment of the S-GA code to make sure these markers are easily matched as start- and end-points.  These are often very long passages. Here is an example of such a passage:
https://frankensteinvariorum.org/viewer/MS/box_c56_chapt_2/#C08_app127 

* Sometimes these are fully rendered in the side panel (as normalized tokens) when they appear inside a single `<app>` in the spine.
* But (as in the example) they are not marked in the reading view because they remain self-closed `<delSpan/>`  elements there.
* Sometimes they don't render properly at all if a `<delSpan>` passage isn't fully incorporated in a single `<app>`. These passages cross multiple `<app> ` elements in the collation.

I do not think we should change the collation to *force* these passages to be held in a single `<app>`. Expanding our `<longToken>` to all the delSpan passages seems inappropriate. These are often extremely long passages in the S-GA. The `<delSpan>` passages are often very lightly marked, sometimes just with a vertical line down the center of the page. I find these markings to be *ambiguous*. It's not clear whether they're really intended as a fully struck out deletion. But they are marked.

To process these more simply, I propose we do NOT attempt to apply horizontal strikethrough marks in the interface. I do not want us to be attempting to process these with regular expressions to strike them out fully.

I prefer to mark them by just indicating the presence of a start-mark and an end-mark where these appear. We can readily do that by *leaving these alone as self-closing marks*. My proposed solution is: *do not attempt to raise the delSpan elements*.

We should:
* Convert `<delSpan spanTo="somewhere"/>` to a sequence of characters in red like: `X--`  
* Convert `<delSpan anchor="#somewhere"/>` to a sequence of characters in red like: `--X`

Make these simple marks appear in the normalized tokens as well. 

Explain all such markings in our introductory legend of markings for the edition.

**Comment by ebeshero** [comment]
To fully re-process these involves changing their output as normalized tokens only. We have been outputting these as normalized `<del>....</del>` in the spine files `@n` attributes.

They are simply being output in the reading view as `<delSpan/>` marks with their attributes, so these should be easy to convert.

**Comment by ebeshero** [comment]
How do we want `<delSpanStart>` and `<delSpanEnd>` markers to be processed?

**Comment by ebeshero** [comment]
`delSpanStart`: X—  
`delSpanEnd`: —X 

color: dark red? (same color as pilcrow mark)

**Comment by ebeshero** [comment]
°—

—°

**Comment by ebeshero** [comment]
https://www.compart.com/en/unicode/U+27DC

⟜

⊸

**Comment by ebeshero** [comment]
✗—

—✗
https://en.wikibooks.org/wiki/Unicode/List_of_useful_symbols

**Comment by Yuying-Jin** [comment]
Resolved now
