### ISSUE TITLE
Annotations 2.0: Migrating Annotations to New Account and Group

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#6]
@mdlincoln will migrate the annotations to a new user that can be shared and edited by the team, and we will create a new private group for these annotations, so we have a clean slate for reviewing annotations. 

When ready, alert @ebeshero @awiscomb @jaquirk.

**Comment by mdlincoln** [comment]
Done, and documented in https://docs.google.com/document/d/1qvR2ayzsZiICEXf0I3TiXJeFp0yQLxN4PcT54whFH6U/edit#heading=h.gjdgxs
