### ISSUE TITLE
Make a quickly searchable view for spine or pre-spine files for Annotations Team

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#7]
@ebeshero will make a search page via XSLT for the Annotations group to quickly look up text strings and see what happens in the other editions. This will make available the text location information, and pretty much output the variorum info in HTML table form. Deletions / insertions are quickly visible as such with a legend.

**Comment by ebeshero** [comment]
Completed with https://github.com/PghFrankenstein/fv-postCollation/commit/5f248499408e910336823d95d624fa89c616e69f and saved to Pittsburgh-Frankenstein docs folder [to serve over our GitHub pages website](https://pghfrankenstein.github.io/Pittsburgh_Frankenstein/). @jaquirk @awiscomb @mdlincoln

**Comment by ebeshero** [comment]
Looking at this, I'd like to add the rest of the novel, working with the uncorrected collation output--so all of it is visible and searchable, even if the alignments are faulty. Having this view is useful for all of us as we're completing our Variorum tasks. For the uncorrected portion, I'll change the background color and post a warning that the collation hasn't been finalized at this point. 

I wrote to you all about possibly adding tunneling annotations directly to this HTML table view. I think they're good for the completed portion of the collation, but I wouldn't advise adding tunneling annotations to anything past that point because the alignment id markers aren't stable. Maybe it's best to look at this view as just that, a searchable but as yet unstable comparison view of the five editions in the Variorum. @jaquirk @awiscomb @mdlincoln

**Comment by ebeshero** [comment]
### Improvements to make on HTML Searchable View of Collation Data
- [x] Make the witnesses appear in consistent chronological order
- [x] Output as much of the novel as possible, and visually distinguish the portion where the collation is uncorrected/unreliable.
- [x] Add a legend indicating the significance of the background colors, and instructions/search advice for how to work with the document.

**Comment by ebeshero** [comment]
Hmmm. Apparently we're not ready to output the entire novel this way, but I'll output as much as I can...(I'm preparing a Readme file about this.)

**Comment by ebeshero** [comment]
Done! Posted on [our GitHub Pages site](https://pghfrankenstein.github.io/Pittsburgh_Frankenstein/) (together with editions the Annotations team is working on with Hypothes.is): <https://pghfrankenstein.github.io/Pittsburgh_Frankenstein/tableView.html>

**Comment by jaquirk** [comment]
Thanks Elisa!

*Jack Quirk | **Ph.D. Student in Literary and Cultural Studies*

Department of English  | Carnegie Mellon University
5000 Forbes Avenue | Baker Hall 259 | Pittsburgh, PA 15213 |*
jquirk@andrew.cmu.edu
<jquirk@andrew.cmu.edu> *

Visit us online at cmu.edu/dietrich/english
